// GENERATED — DO NOT EDIT.
// Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
// Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
// Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
// See generated/sdk-registry/README.md for the rules this data is fed to.

pub const REGISTRY_VERSION: &str = "1.2.0";
pub const CONTENT_HASH: &str = "cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26";

// The keyword gate is ASYMMETRIC — see README.md, rule 3.
pub const KEYWORD_WINDOW_BEFORE: usize = 60;
pub const KEYWORD_WINDOW_AFTER: usize = 40;
pub const CONTEXT_WINDOW: usize = 60;
pub const LABEL_WINDOW: usize = 60;
pub const LABEL_REACH: usize = 25;

pub const NEAR_MISS_REDACTION: &str = "[NATIONAL_ID_REDACTED]";
pub const NEAR_MISS_TYPE: &str = "national_id_near_miss";
pub static NEAR_MISS_KINDS: &[&str] = &["health_id", "national_id", "tax_id"];

pub static TABLE_DELIMITERS: &[&str] = &["\t", "|", ";", ","];
pub const TABLE_MAX_HEADER_LENGTH: usize = 32;
pub const TABLE_MAX_HEADER_WORDS: usize = 4;
pub const TABLE_MIN_ROWS: usize = 3;
pub const TABLE_MIN_COMMA_COLUMNS: usize = 3;

pub static LABELS: &[&str] = &[
    r#"AADHAAR"#,
    r#"ABN"#,
    r#"ACN"#,
    r#"BVN"#,
    r#"CA_PASSPORT"#,
    r#"CA_PHONE"#,
    r#"CA_POSTAL"#,
    r#"CNIC"#,
    r#"CNPJ"#,
    r#"CODICE_FISCALE"#,
    r#"CPF"#,
    r#"EMIRATES_ID"#,
    r#"GHANA_CARD"#,
    r#"IFSC"#,
    r#"ITIN"#,
    r#"KRA_PIN"#,
    r#"MEDICARE"#,
    r#"MYKAD"#,
    r#"MY_NUMBER"#,
    r#"NATIONAL_ID"#,
    r#"NHS"#,
    r#"NIK"#,
    r#"NIN"#,
    r#"NINO"#,
    r#"NRIC"#,
    r#"PAN"#,
    r#"PASSPORT"#,
    r#"PHONE"#,
    r#"PINCODE"#,
    r#"PO_BOX"#,
    r#"RESIDENT_ID"#,
    r#"RFC"#,
    r#"RRN"#,
    r#"SIN"#,
    r#"SORT_CODE"#,
    r#"TAN"#,
    r#"TAX_ID"#,
    r#"TFN"#,
    r#"UK_POSTCODE"#,
    r#"ZA_ID"#,
];

pub static REFERENCE_LABELS: &[&str] = &[
    r#"order"#,
    r#"invoice"#,
    r#"purchase order"#,
    r#"po no"#,
    r#"po number"#,
    r#"job number"#,
    r#"job no"#,
    r#"booking"#,
    r#"tracking"#,
    r#"consignment"#,
    r#"waybill"#,
    r#"airway bill"#,
    r#"awb"#,
    r#"docket"#,
    r#"quote"#,
    r#"quotation"#,
    r#"ticket"#,
    r#"receipt"#,
    r#"serial number"#,
    r#"asset tag"#,
    r#"part number"#,
    r#"stock code"#,
    r#"batch"#,
    r#"shipment"#,
    r#"dispatch note"#,
    r#"delivery note"#,
    r#"work order"#,
    r#"contract number"#,
    r#"policy number"#,
    r#"meter number"#,
    r#"case id"#,
    r#"bestelling"#,
    r#"bestelnommer"#,
    r#"faktuur"#,
    r#"kwotasie"#,
    r#"commande"#,
    r#"facture"#,
    r#"devis"#,
    r#"bon de livraison"#,
    r#"expédition"#,
    r#"expedition"#,
    r#"pedido"#,
    r#"fatura"#,
    r#"factura"#,
    r#"orçamento"#,
    r#"orcamento"#,
    r#"presupuesto"#,
    r#"remito"#,
    r#"pesanan"#,
    r#"nombor pesanan"#,
    r#"invois"#,
    r#"sebut harga"#,
    r#"penghantaran"#,
    r#"resit"#,
    r#"आदेश"#,
    r#"क्रय आदेश"#,
    r#"चालान"#,
    r#"कोटेशन"#,
    r#"रसीद"#,
    r#"آرڈر"#,
    r#"انوائس"#,
    r#"رسید"#,
    r#"کوٹیشن"#,
    r#"ترسیل"#,
    r#"طلب"#,
    r#"أمر شراء"#,
    r#"فاتورة"#,
    r#"عرض سعر"#,
    r#"إيصال"#,
    r#"شحنة"#,
    r#"بوليصة"#,
    r#"注文"#,
    r#"注文番号"#,
    r#"発注"#,
    r#"発注番号"#,
    r#"請求書"#,
    r#"請求番号"#,
    r#"伝票"#,
    r#"伝票番号"#,
    r#"見積"#,
    r#"見積番号"#,
    r#"管理番号"#,
    r#"在庫番号"#,
    r#"受注"#,
    r#"出荷"#,
    r#"订单"#,
    r#"訂單"#,
    r#"订单编号"#,
    r#"訂單編號"#,
    r#"发票"#,
    r#"發票"#,
    r#"采购"#,
    r#"採購"#,
    r#"报价"#,
    r#"報價"#,
    r#"运单"#,
    r#"運單"#,
    r#"物料编号"#,
    r#"物料編號"#,
    r#"库存"#,
    r#"庫存"#,
    r#"주문"#,
    r#"주문번호"#,
    r#"구매주문"#,
    r#"송장"#,
    r#"견적"#,
    r#"견적서"#,
    r#"운송장"#,
    r#"자재번호"#,
    r#"재고번호"#,
    r#"ใบสั่งซื้อ"#,
    r#"เลขที่ใบสั่งซื้อ"#,
    r#"ใบแจ้งหนี้"#,
    r#"ใบเสนอราคา"#,
    r#"ใบส่งของ"#,
    r#"รหัสพัสดุ"#,
    r#"ใบงาน"#,
];

pub static GENERIC_ID_KEYWORDS: &[&str] = &[
    r#"national id"#,
    r#"national identity"#,
    r#"national identification"#,
    r#"national number"#,
    r#"national code"#,
    r#"identity number"#,
    r#"identification number"#,
    r#"id number"#,
    r#"citizen id"#,
    r#"citizen number"#,
    r#"resident id"#,
    r#"resident number"#,
    r#"civil id"#,
    r#"civil number"#,
    r#"civil registration"#,
    r#"personal number"#,
    r#"personal identity"#,
    r#"personal code"#,
    r#"personal id"#,
    r#"tax identification"#,
    r#"tax reference"#,
    r#"taxpayer number"#,
    r#"taxpayer id"#,
];

pub static LOCAL_ID_KEYWORDS: &[&str] = &[
    r#"cedula"#,
    r#"cédula"#,
    r#"iqama"#,
    r#"nadra"#,
    r#"cnic"#,
    r#"aadhaar"#,
    r#"voen"#,
    r#"vöen"#,
    r#"егн"#,
    r#"oib"#,
    r#"cpr-nummer"#,
    r#"cpr nummer"#,
    r#"kennitala"#,
    r#"personnummer"#,
    r#"adoazonosito"#,
    r#"adóazonosító"#,
    r#"szemelyi azonosito"#,
    r#"személyi azonosító"#,
    r#"kimlik"#,
    r#"рнокпп"#,
    r#"nid number"#,
    r#"sars income tax"#,
];

pub struct Country {
    pub code: &'static str,
    pub name: &'static str,
    pub calling_code: &'static str,
    pub bloc: bool,
    pub patterns: &'static [&'static str],
}

pub static COUNTRIES: &[Country] = &[
    Country { code: r#"AU"#, name: r#"Australia"#, calling_code: r#"61"#, bloc: false, patterns: &[r#"au_tfn"#, r#"au_abn"#, r#"au_medicare"#, r#"au_acn"#, r#"au_phone_intl"#] },
    Country { code: r#"US"#, name: r#"United States"#, calling_code: r#"1"#, bloc: false, patterns: &[r#"us_itin"#, r#"us_passport_alpha"#] },
    Country { code: r#"GB"#, name: r#"United Kingdom"#, calling_code: r#"44"#, bloc: false, patterns: &[r#"uk_phone_full"#, r#"uk_sort_code"#, r#"uk_nino"#, r#"uk_nhs"#, r#"uk_postcode"#] },
    Country { code: r#"EU"#, name: r#"European Union"#, calling_code: r#""#, bloc: true, patterns: &[r#"de_tax_id"#] },
    Country { code: r#"AE"#, name: r#"United Arab Emirates"#, calling_code: r#"971"#, bloc: false, patterns: &[r#"emirates_id"#, r#"uae_phone"#, r#"uae_landline"#, r#"po_box"#] },
    Country { code: r#"SA"#, name: r#"Saudi Arabia"#, calling_code: r#"966"#, bloc: false, patterns: &[r#"sa_national_id"#, r#"sa_phone"#] },
    Country { code: r#"NG"#, name: r#"Nigeria"#, calling_code: r#"234"#, bloc: false, patterns: &[r#"ng_nin"#, r#"ng_bvn"#, r#"ng_phone"#] },
    Country { code: r#"IN"#, name: r#"India"#, calling_code: r#"91"#, bloc: false, patterns: &[r#"in_aadhaar"#, r#"in_pan"#, r#"in_phone"#, r#"in_ifsc"#, r#"in_pincode"#] },
    Country { code: r#"JP"#, name: r#"Japan"#, calling_code: r#"81"#, bloc: false, patterns: &[r#"jp_my_number"#, r#"jp_phone_intl"#, r#"jp_phone_national"#] },
    Country { code: r#"CN"#, name: r#"China"#, calling_code: r#"86"#, bloc: false, patterns: &[r#"cn_resident_id"#, r#"cn_phone_intl"#, r#"cn_phone_national"#] },
    Country { code: r#"KR"#, name: r#"South Korea"#, calling_code: r#"82"#, bloc: false, patterns: &[r#"kr_rrn"#, r#"kr_phone_intl"#, r#"kr_phone_national"#] },
    Country { code: r#"BR"#, name: r#"Brazil"#, calling_code: r#"55"#, bloc: false, patterns: &[r#"br_cpf"#, r#"br_cnpj"#] },
    Country { code: r#"CA"#, name: r#"Canada"#, calling_code: r#"1"#, bloc: false, patterns: &[r#"ca_sin"#, r#"ca_phone"#, r#"ca_postal_code"#, r#"ca_passport"#] },
    Country { code: r#"ZA"#, name: r#"South Africa"#, calling_code: r#"27"#, bloc: false, patterns: &[r#"za_id_number"#, r#"za_phone"#] },
    Country { code: r#"GH"#, name: r#"Ghana"#, calling_code: r#"233"#, bloc: false, patterns: &[r#"gh_ghana_card"#] },
    Country { code: r#"IT"#, name: r#"Italy"#, calling_code: r#"39"#, bloc: false, patterns: &[r#"it_codice_fiscale"#] },
    Country { code: r#"KE"#, name: r#"Kenya"#, calling_code: r#"254"#, bloc: false, patterns: &[r#"ke_kra_pin"#] },
    Country { code: r#"MU"#, name: r#"Mauritius"#, calling_code: r#"230"#, bloc: false, patterns: &[r#"mu_tan"#] },
    Country { code: r#"MX"#, name: r#"Mexico"#, calling_code: r#"52"#, bloc: false, patterns: &[r#"mx_rfc"#] },
    Country { code: r#"MY"#, name: r#"Malaysia"#, calling_code: r#"60"#, bloc: false, patterns: &[r#"my_mykad"#] },
    Country { code: r#"PK"#, name: r#"Pakistan"#, calling_code: r#"92"#, bloc: false, patterns: &[r#"pk_cnic"#] },
    Country { code: r#"SG"#, name: r#"Singapore"#, calling_code: r#"65"#, bloc: false, patterns: &[r#"sg_nric"#] },
    Country { code: r#"TH"#, name: r#"Thailand"#, calling_code: r#"66"#, bloc: false, patterns: &[r#"th_national_id"#] },
    Country { code: r#"ID"#, name: r#"Indonesia"#, calling_code: r#"62"#, bloc: false, patterns: &[r#"id_nik"#] },
];

pub struct Pattern {
    pub name: &'static str,
    pub country: &'static str,
    pub kind: &'static str,
    pub regex: &'static str,
    pub redaction: &'static str,
    pub pii_type: &'static str,
    pub label: &'static str,
    pub requires_keyword: bool,
    pub always_on: bool,
    pub keywords: &'static [&'static str],
    pub whole_word_keywords: &'static [&'static str],
    pub near_miss_keywords: &'static [&'static str],
    pub near_miss_fallback: bool,
    pub checksum: Option<&'static str>,
    pub checksum_required: bool,
}

// The `regex` crate has no lookaround; every pattern here is written without it.
pub static PATTERNS: &[Pattern] = &[
    Pattern {
        name: r#"au_tfn"#,
        country: r#"AU"#,
        kind: r#"tax_id"#,
        regex: r#"\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: r#"[TFN_REDACTED]"#,
        pii_type: r#"au_tfn"#,
        label: r#"TFN"#,
        requires_keyword: true,
        always_on: true,
        keywords: &[r#"tfn"#, r#"tax file"#, r#"tax number"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"au_tfn"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"au_abn"#,
        country: r#"AU"#,
        kind: r#"company"#,
        regex: r#"\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: r#"[ABN_REDACTED]"#,
        pii_type: r#"au_abn"#,
        label: r#"ABN"#,
        requires_keyword: true,
        always_on: true,
        keywords: &[r#"abn"#, r#"business number"#, r#"australian business"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"au_abn"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"au_medicare"#,
        country: r#"AU"#,
        kind: r#"health_id"#,
        regex: r#"\b\d{4}[ \t]?\d{5}[ \t]?\d{1}\b"#,
        redaction: r#"[MEDICARE_REDACTED]"#,
        pii_type: r#"au_medicare"#,
        label: r#"MEDICARE"#,
        requires_keyword: true,
        always_on: true,
        keywords: &[r#"medicare"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"au_medicare"#),
        checksum_required: false,
    },
    Pattern {
        name: r#"au_acn"#,
        country: r#"AU"#,
        kind: r#"company"#,
        regex: r#"\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: r#"[ACN_REDACTED]"#,
        pii_type: r#"au_acn"#,
        label: r#"ACN"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"acn"#, r#"company number"#, r#"australian company"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"au_phone_intl"#,
        country: r#"AU"#,
        kind: r#"phone"#,
        regex: r#"\+61[ \t]?[2-478](?:[ \t]?\d){8}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"au_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"us_itin"#,
        country: r#"US"#,
        kind: r#"tax_id"#,
        regex: r#"\b9\d{2}-[7-9]\d-\d{4}\b"#,
        redaction: r#"[ITIN_REDACTED]"#,
        pii_type: r#"us_itin"#,
        label: r#"ITIN"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"us_passport_alpha"#,
        country: r#"US"#,
        kind: r#"passport"#,
        regex: r#"\b[A-Z]\d{8}\b"#,
        redaction: r#"[PASSPORT_REDACTED]"#,
        pii_type: r#"us_passport"#,
        label: r#"PASSPORT"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"passport"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"uk_phone_full"#,
        country: r#"GB"#,
        kind: r#"phone"#,
        regex: r#"(?:\+44[ \t]?|\b0)(?:7\d{3}|\d{2,4})[ \t]?\d{3,4}[ \t]?\d{3,4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"uk_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"uk_sort_code"#,
        country: r#"GB"#,
        kind: r#"bank"#,
        regex: r#"\b\d{2}-\d{2}-\d{2}\b"#,
        redaction: r#"[SORT_CODE_REDACTED]"#,
        pii_type: r#"uk_sort_code"#,
        label: r#"SORT_CODE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"sort code"#, r#"sort-code"#, r#"bank"#, r#"account"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"uk_nino"#,
        country: r#"GB"#,
        kind: r#"national_id"#,
        regex: r#"\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b"#,
        redaction: r#"[NINO_REDACTED]"#,
        pii_type: r#"national_id"#,
        label: r#"NINO"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"national insurance"#, r#"ni number"#, r#"nino"#, r#"ni:"#, r#"insurance number"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"uk_nhs"#,
        country: r#"GB"#,
        kind: r#"health_id"#,
        regex: r#"\b\d{3}[ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: r#"[NHS_REDACTED]"#,
        pii_type: r#"health_id"#,
        label: r#"NHS"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"nhs"#, r#"national health"#, r#"nhs number"#, r#"health service"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"uk_nhs"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"uk_postcode"#,
        country: r#"GB"#,
        kind: r#"postcode"#,
        regex: r#"\b[A-Z]{1,2}\d[A-Z\d]?[ \t]?\d[A-Z]{2}\b"#,
        redaction: r#"[UK_POSTCODE_REDACTED]"#,
        pii_type: r#"postal_code"#,
        label: r#"UK_POSTCODE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"postcode"#, r#"post code"#, r#"uk"#, r#"united kingdom"#, r#"britain"#, r#"england"#, r#"scotland"#, r#"wales"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"de_tax_id"#,
        country: r#"EU"#,
        kind: r#"tax_id"#,
        regex: r#"\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b"#,
        redaction: r#"[TAX_ID_REDACTED]"#,
        pii_type: r#"de_tax_id"#,
        label: r#"TAX_ID"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"steuer"#, r#"tax id"#, r#"steuernummer"#, r#"idnr"#, r#"steueridentifikation"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"de_steuer_id"#),
        checksum_required: false,
    },
    Pattern {
        name: r#"emirates_id"#,
        country: r#"AE"#,
        kind: r#"national_id"#,
        regex: r#"\b784-?\d{4}-?\d{7}-?\d\b"#,
        redaction: r#"[EMIRATES_ID_REDACTED]"#,
        pii_type: r#"emirates_id"#,
        label: r#"EMIRATES_ID"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"ae_emirates_id"#),
        checksum_required: false,
    },
    Pattern {
        name: r#"uae_phone"#,
        country: r#"AE"#,
        kind: r#"phone"#,
        regex: r#"(?:\+971[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"uae_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"uae_landline"#,
        country: r#"AE"#,
        kind: r#"phone"#,
        regex: r#"(?:\+971[ \t]?|\b0)[2-4679][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"uae_landline"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"po_box"#,
        country: r#"AE"#,
        kind: r#"postcode"#,
        regex: r#"\b[Pp]\.?[Oo]\.?[ \t]*[Bb]ox[ \t]+\d{3,6}\b"#,
        redaction: r#"[PO_BOX_REDACTED]"#,
        pii_type: r#"po_box"#,
        label: r#"PO_BOX"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"sa_national_id"#,
        country: r#"SA"#,
        kind: r#"national_id"#,
        regex: r#"\b[12]\d{9}\b"#,
        redaction: r#"[NATIONAL_ID_REDACTED]"#,
        pii_type: r#"sa_national_id"#,
        label: r#"NATIONAL_ID"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"national id"#, r#"iqama"#, r#"national identification"#, r#"resident id"#, r#"saudi id"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"sa_national_id"#),
        checksum_required: false,
    },
    Pattern {
        name: r#"sa_phone"#,
        country: r#"SA"#,
        kind: r#"phone"#,
        regex: r#"(?:\+966[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"sa_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"ng_nin"#,
        country: r#"NG"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{11}\b"#,
        redaction: r#"[NIN_REDACTED]"#,
        pii_type: r#"ng_nin"#,
        label: r#"NIN"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"nin"#, r#"national id"#, r#"national identification"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"ng_bvn"#,
        country: r#"NG"#,
        kind: r#"bank"#,
        regex: r#"\b\d{11}\b"#,
        redaction: r#"[BVN_REDACTED]"#,
        pii_type: r#"ng_bvn"#,
        label: r#"BVN"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"bvn"#, r#"bank verification"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"ng_phone"#,
        country: r#"NG"#,
        kind: r#"phone"#,
        regex: r#"(?:\+234[ \t]?|\b0)[789]0[1-9][ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"ng_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"in_aadhaar"#,
        country: r#"IN"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b"#,
        redaction: r#"[AADHAAR_REDACTED]"#,
        pii_type: r#"in_aadhaar"#,
        label: r#"AADHAAR"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"aadhaar"#, r#"aadhar"#, r#"uid"#, r#"unique identification"#, r#"aadhaar number"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"verhoeff"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"in_pan"#,
        country: r#"IN"#,
        kind: r#"tax_id"#,
        regex: r#"\b[A-Z]{5}\d{4}[A-Z]\b"#,
        redaction: r#"[PAN_REDACTED]"#,
        pii_type: r#"in_pan"#,
        label: r#"PAN"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"in_phone"#,
        country: r#"IN"#,
        kind: r#"phone"#,
        regex: r#"(?:\+91[ \t]?|\b0|\b)[6-9]\d{4}[ \t]?\d{5}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"in_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"in_ifsc"#,
        country: r#"IN"#,
        kind: r#"bank"#,
        regex: r#"\b[A-Z]{4}0[A-Z0-9]{6}\b"#,
        redaction: r#"[IFSC_REDACTED]"#,
        pii_type: r#"in_ifsc"#,
        label: r#"IFSC"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"in_pincode"#,
        country: r#"IN"#,
        kind: r#"postcode"#,
        regex: r#"\b[1-9]\d{5}\b"#,
        redaction: r#"[PINCODE_REDACTED]"#,
        pii_type: r#"in_pincode"#,
        label: r#"PINCODE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"pin code"#, r#"pincode"#, r#"postal code"#, r#"zip"#, r#"address"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"jp_my_number"#,
        country: r#"JP"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b"#,
        redaction: r#"[MY_NUMBER_REDACTED]"#,
        pii_type: r#"jp_my_number"#,
        label: r#"MY_NUMBER"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"my number"#, r#"individual number"#, r#"マイナンバー"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"jp_my_number"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"jp_phone_intl"#,
        country: r#"JP"#,
        kind: r#"phone"#,
        regex: r#"\+81[ \t-]?[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"jp_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"jp_phone_national"#,
        country: r#"JP"#,
        kind: r#"phone"#,
        regex: r#"\b0[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"jp_phone"#,
        label: r#"PHONE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"phone"#, r#"telephone"#, r#"tel"#, r#"mobile"#, r#"cell"#, r#"fax"#, r#"call"#, r#"contact"#, r#"whatsapp"#, r#"hotline"#, r#"landline"#, r#"電話"#, r#"電話番号"#, r#"携帯"#, r#"携帯番号"#, r#"でんわ"#, r#"电话"#, r#"手机"#, r#"手機"#, r#"전화"#, r#"휴대"#, r#"휴대폰"#, r#"연락처"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"cn_resident_id"#,
        country: r#"CN"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{6}(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[0-9Xx]\b"#,
        redaction: r#"[RESIDENT_ID_REDACTED]"#,
        pii_type: r#"cn_resident_id"#,
        label: r#"RESIDENT_ID"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"resident id"#, r#"resident identity"#, r#"identity card"#, r#"id card"#, r#"national id"#, r#"id number"#, r#"id no"#, r#"id:"#, r#"id ="#, r#"identity number"#, r#"hukou"#, r#"身份证"#, r#"身份證"#, r#"居民身份证"#, r#"居民身份證"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"cn_resident_id"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"cn_phone_intl"#,
        country: r#"CN"#,
        kind: r#"phone"#,
        regex: r#"\+86[ \t-]?1[3-9]\d{9}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"cn_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"cn_phone_national"#,
        country: r#"CN"#,
        kind: r#"phone"#,
        regex: r#"\b1[3-9]\d{9}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"cn_phone"#,
        label: r#"PHONE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"phone"#, r#"telephone"#, r#"tel"#, r#"mobile"#, r#"cell"#, r#"fax"#, r#"call"#, r#"contact"#, r#"whatsapp"#, r#"hotline"#, r#"landline"#, r#"電話"#, r#"電話番号"#, r#"携帯"#, r#"携帯番号"#, r#"でんわ"#, r#"电话"#, r#"手机"#, r#"手機"#, r#"전화"#, r#"휴대"#, r#"휴대폰"#, r#"연락처"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"kr_rrn"#,
        country: r#"KR"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{6}-?[1-4]\d{6}\b"#,
        redaction: r#"[RRN_REDACTED]"#,
        pii_type: r#"kr_rrn"#,
        label: r#"RRN"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"resident registration"#, r#"resident number"#, r#"registration number"#, r#"rrn"#, r#"jumin"#, r#"juminbeonho"#, r#"national id"#, r#"id number"#, r#"id no"#, r#"id:"#, r#"id ="#, r#"identity number"#, r#"주민등록번호"#, r#"주민번호"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"kr_rrn"#),
        checksum_required: false,
    },
    Pattern {
        name: r#"kr_phone_intl"#,
        country: r#"KR"#,
        kind: r#"phone"#,
        regex: r#"\+82[ \t-]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"kr_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"kr_phone_national"#,
        country: r#"KR"#,
        kind: r#"phone"#,
        regex: r#"\b01[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"kr_phone"#,
        label: r#"PHONE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"phone"#, r#"telephone"#, r#"tel"#, r#"mobile"#, r#"cell"#, r#"fax"#, r#"call"#, r#"contact"#, r#"whatsapp"#, r#"hotline"#, r#"landline"#, r#"電話"#, r#"電話番号"#, r#"携帯"#, r#"携帯番号"#, r#"でんわ"#, r#"电话"#, r#"手机"#, r#"手機"#, r#"전화"#, r#"휴대"#, r#"휴대폰"#, r#"연락처"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"br_cpf"#,
        country: r#"BR"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b"#,
        redaction: r#"[CPF_REDACTED]"#,
        pii_type: r#"br_cpf"#,
        label: r#"CPF"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[r#"cpf"#, r#"cadastro de pessoas"#, r#"receita federal"#],
        near_miss_fallback: true,
        checksum: Some(r#"br_cpf"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"br_cnpj"#,
        country: r#"BR"#,
        kind: r#"company"#,
        regex: r#"\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b"#,
        redaction: r#"[CNPJ_REDACTED]"#,
        pii_type: r#"br_cnpj"#,
        label: r#"CNPJ"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"br_cnpj"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"ca_sin"#,
        country: r#"CA"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{3}[- \t]\d{3}[- \t]\d{3}\b"#,
        redaction: r#"[SIN_REDACTED]"#,
        pii_type: r#"ca_sin"#,
        label: r#"SIN"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[r#"sin"#, r#"social insurance"#, r#"canada revenue"#, r#"cra"#, r#"employment insurance"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: Some(r#"ca_sin"#),
        checksum_required: false,
    },
    Pattern {
        name: r#"ca_phone"#,
        country: r#"CA"#,
        kind: r#"phone"#,
        regex: r#"\b(\+?1[-. \t]?)?\(?\d{3}\)?[-. \t]\d{3}[-. \t]\d{4}\b"#,
        redaction: r#"[CA_PHONE_REDACTED]"#,
        pii_type: r#"phone"#,
        label: r#"CA_PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[r#"phone"#, r#"mobile"#, r#"cell"#, r#"tel"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"ca_postal_code"#,
        country: r#"CA"#,
        kind: r#"postcode"#,
        regex: r#"\b[A-Za-z]\d[A-Za-z][ \t-]?\d[A-Za-z]\d\b"#,
        redaction: r#"[CA_POSTAL_REDACTED]"#,
        pii_type: r#"postal_code"#,
        label: r#"CA_POSTAL"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[r#"postal"#, r#"zip"#, r#"post code"#, r#"mailing"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"ca_passport"#,
        country: r#"CA"#,
        kind: r#"passport"#,
        regex: r#"\b[A-Za-z]{2}\d{6}\b"#,
        redaction: r#"[CA_PASSPORT_REDACTED]"#,
        pii_type: r#"passport"#,
        label: r#"CA_PASSPORT"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"passport"#, r#"travel document"#, r#"citizenship"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"za_id_number"#,
        country: r#"ZA"#,
        kind: r#"national_id"#,
        regex: r#"\b(\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])(\d{4})(0|1)(\d{2})\b"#,
        redaction: r#"[ZA_ID_REDACTED]"#,
        pii_type: r#"za_id_number"#,
        label: r#"ZA_ID"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[r#"sa id"#, r#"rsa id"#, r#"south african id"#, r#"suid-afrikaanse id"#, r#"id no"#, r#"id-nommer"#, r#"home affairs"#],
        near_miss_fallback: true,
        checksum: Some(r#"za_id"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"za_phone"#,
        country: r#"ZA"#,
        kind: r#"phone"#,
        regex: r#"(?:\+27[ \t]?|\b0)[6-8]\d[ \t]?\d{3}[ \t]?\d{4}\b"#,
        redaction: r#"[PHONE_REDACTED]"#,
        pii_type: r#"za_phone"#,
        label: r#"PHONE"#,
        requires_keyword: false,
        always_on: false,
        keywords: &[],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"gh_ghana_card"#,
        country: r#"GH"#,
        kind: r#"national_id"#,
        regex: r#"\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b"#,
        redaction: r#"[GHANA_CARD_REDACTED]"#,
        pii_type: r#"gh_ghana_card"#,
        label: r#"GHANA_CARD"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"ghana card"#, r#"ghanacard"#, r#"ghana revenue"#, r#"nia pin"#, r#"personal id number"#, r#"gra tin"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"it_codice_fiscale"#,
        country: r#"IT"#,
        kind: r#"tax_id"#,
        regex: r#"\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b"#,
        redaction: r#"[CODICE_FISCALE_REDACTED]"#,
        pii_type: r#"it_codice_fiscale"#,
        label: r#"CODICE_FISCALE"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"codice fiscale"#, r#"cod. fisc"#, r#"cod.fisc"#, r#"c.f."#, r#"anagrafe tributaria"#, r#"tessera sanitaria"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"it_codice_fiscale"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"ke_kra_pin"#,
        country: r#"KE"#,
        kind: r#"tax_id"#,
        regex: r#"\b[AP]\d{9}[A-Z]\b"#,
        redaction: r#"[KRA_PIN_REDACTED]"#,
        pii_type: r#"ke_kra_pin"#,
        label: r#"KRA_PIN"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"kra pin"#, r#"kra"#, r#"tax pin"#, r#"itax"#, r#"pin certificate"#, r#"personal identification number"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"mu_tan"#,
        country: r#"MU"#,
        kind: r#"tax_id"#,
        regex: r#"\b[123578]\d{7}\b"#,
        redaction: r#"[TAN_REDACTED]"#,
        pii_type: r#"mu_tan"#,
        label: r#"TAN"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"tax account number"#, r#"mauritius revenue"#, r#"tan "#, r#"tan:"#, r#"tan no"#, r#"tan number"#, r#"mra tan"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"mx_rfc"#,
        country: r#"MX"#,
        kind: r#"tax_id"#,
        regex: r#"\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b"#,
        redaction: r#"[RFC_REDACTED]"#,
        pii_type: r#"mx_rfc"#,
        label: r#"RFC"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"rfc"#, r#"homoclave"#, r#"registro federal de contribuyentes"#, r#"contribuyentes"#, r#"constancia de situación fiscal"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"my_mykad"#,
        country: r#"MY"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{6}-?\d{2}-?\d{4}\b"#,
        redaction: r#"[MYKAD_REDACTED]"#,
        pii_type: r#"my_mykad"#,
        label: r#"MYKAD"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"mykad"#, r#"my kad"#, r#"kad pengenalan"#, r#"no. kad pengenalan"#, r#"nric"#, r#"ic number"#, r#"no. ic"#, r#"mykid"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"pk_cnic"#,
        country: r#"PK"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{5}-?\d{7}-?\d\b"#,
        redaction: r#"[CNIC_REDACTED]"#,
        pii_type: r#"pk_cnic"#,
        label: r#"CNIC"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"cnic"#, r#"nadra"#, r#"nic number"#, r#"identity card number"#, r#"شناختی کارڈ"#, r#"شناختی"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
    Pattern {
        name: r#"sg_nric"#,
        country: r#"SG"#,
        kind: r#"national_id"#,
        regex: r#"\b[STFGM]\d{7}[A-Z]\b"#,
        redaction: r#"[NRIC_REDACTED]"#,
        pii_type: r#"sg_nric"#,
        label: r#"NRIC"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"nric"#, r#"fin number"#, r#"fin no"#, r#"fin:"#, r#"identity card"#, r#"identification number"#, r#"cpf"#, r#"singpass"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"sg_nric"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"th_national_id"#,
        country: r#"TH"#,
        kind: r#"national_id"#,
        regex: r#"\b\d-?\d{4}-?\d{5}-?\d{2}-?\d\b"#,
        redaction: r#"[NATIONAL_ID_REDACTED]"#,
        pii_type: r#"th_national_id"#,
        label: r#"NATIONAL_ID"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"national id"#, r#"thai id"#, r#"เลขประจำตัวประชาชน"#, r#"บัตรประชาชน"#, r#"เลขบัตร"#, r#"promptpay"#],
        whole_word_keywords: &[],
        near_miss_keywords: &[],
        near_miss_fallback: true,
        checksum: Some(r#"th_national_id"#),
        checksum_required: true,
    },
    Pattern {
        name: r#"id_nik"#,
        country: r#"ID"#,
        kind: r#"national_id"#,
        regex: r#"\b\d{16}\b"#,
        redaction: r#"[NIK_REDACTED]"#,
        pii_type: r#"id_nik"#,
        label: r#"NIK"#,
        requires_keyword: true,
        always_on: false,
        keywords: &[r#"nomor induk kependudukan"#, r#"kartu tanda penduduk"#, r#"dukcapil"#],
        whole_word_keywords: &[r#"nik"#, r#"e-ktp"#, r#"ektp"#, r#"ktp"#, r#"npwp"#],
        near_miss_keywords: &[],
        near_miss_fallback: false,
        checksum: None,
        checksum_required: false,
    },
];

pub struct Signal {
    pub country: &'static str,
    pub regex: &'static str,
    pub flags: &'static str,
    pub keywords: &'static [&'static str],
    pub whole_word_keywords: &'static [&'static str],
    pub activates: &'static str,
}

// SIGNALS is in evaluation order. Stop at the first signal a country matches.
pub static SIGNALS: &[Signal] = &[
    Signal {
        country: r#"AU"#,
        regex: r#"\b\d{3}\s\d{3}\s\d{3}\b"#,
        flags: r#""#,
        keywords: &[r#"tfn"#, r#"tax file"#, r#"medicare"#],
        whole_word_keywords: &[],
        activates: r#"AU"#,
    },
    Signal {
        country: r#"AU"#,
        regex: r#"\b\d{4}\s\d{5}\s\d{1}\b"#,
        flags: r#""#,
        keywords: &[],
        whole_word_keywords: &[],
        activates: r#"AU"#,
    },
    Signal {
        country: r#"AU"#,
        regex: r#"\b(0[2-9]|\+61)\d{8,9}\b"#,
        flags: r#""#,
        keywords: &[r#"au"#, r#"australia"#, r#"australian"#],
        whole_word_keywords: &[],
        activates: r#"AU"#,
    },
    Signal {
        country: r#"GB"#,
        regex: r#"\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b"#,
        flags: r#"i"#,
        keywords: &[r#"national insurance"#, r#"ni number"#, r#"nino"#, r#"ni:"#],
        whole_word_keywords: &[],
        activates: r#"GB"#,
    },
    Signal {
        country: r#"GB"#,
        regex: r#"\b[A-Z]{1,2}\d{1,2}[ \t]?\d[A-Z]{2}\b"#,
        flags: r#""#,
        keywords: &[r#"uk"#, r#"united kingdom"#, r#"britain"#, r#"postcode"#],
        whole_word_keywords: &[],
        activates: r#"GB"#,
    },
    Signal {
        country: r#"GB"#,
        regex: r#"\b(\+44|0044)\d{10}\b"#,
        flags: r#""#,
        keywords: &[r#"uk"#, r#"united kingdom"#, r#"britain"#],
        whole_word_keywords: &[],
        activates: r#"GB"#,
    },
    Signal {
        country: r#"CA"#,
        regex: r#"\b\d{3}[- \t]\d{3}[- \t]\d{3}\b"#,
        flags: r#""#,
        keywords: &[r#"sin"#, r#"social insurance"#, r#"canada revenue"#, r#"cra"#, r#"employment insurance"#],
        whole_word_keywords: &[],
        activates: r#"CA"#,
    },
    Signal {
        country: r#"CA"#,
        regex: r#"\b[A-Za-z]\d[A-Za-z][ \t]?\d[A-Za-z]\d\b"#,
        flags: r#""#,
        keywords: &[r#"canada"#, r#"canadian"#, r#"postal code"#, r#"province"#],
        whole_word_keywords: &[],
        activates: r#"CA"#,
    },
    Signal {
        country: r#"ZA"#,
        regex: r#"\b\d{13}\b"#,
        flags: r#""#,
        keywords: &[r#"id number"#, r#"identity number"#, r#"south africa"#, r#"sa id"#, r#"rsa"#, r#"popia"#, r#"fica"#],
        whole_word_keywords: &[],
        activates: r#"ZA"#,
    },
    Signal {
        country: r#"ZA"#,
        regex: r#"\b(\+27|0)[6-8]\d{8}\b"#,
        flags: r#""#,
        keywords: &[r#"south africa"#, r#"za"#, r#"johannesburg"#, r#"cape town"#, r#"durban"#, r#"pretoria"#],
        whole_word_keywords: &[],
        activates: r#"ZA"#,
    },
    Signal {
        country: r#"DE"#,
        regex: r#"\b[1-9]\d{10}\b"#,
        flags: r#""#,
        keywords: &[r#"steuer"#, r#"steuernummer"#, r#"finanzamt"#, r#"tax id"#, r#"german"#],
        whole_word_keywords: &[],
        activates: r#"DE"#,
    },
    Signal {
        country: r#"DE"#,
        regex: r#"\b(\+49|0049)\d{10,11}\b"#,
        flags: r#""#,
        keywords: &[r#"germany"#, r#"german"#, r#"deutschland"#, r#"de"#],
        whole_word_keywords: &[],
        activates: r#"DE"#,
    },
    Signal {
        country: r#"NG"#,
        regex: r#"\b\d{11}\b"#,
        flags: r#""#,
        keywords: &[r#"bvn"#, r#"nin"#, r#"bank verification"#, r#"nigeria"#, r#"nigerian"#],
        whole_word_keywords: &[],
        activates: r#"NG"#,
    },
    Signal {
        country: r#"NG"#,
        regex: r#"\b(\+234|0)[7-9]\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"nigeria"#, r#"nigerian"#, r#"lagos"#, r#"abuja"#],
        whole_word_keywords: &[],
        activates: r#"NG"#,
    },
    Signal {
        country: r#"AE"#,
        regex: r#"\b784[- \t]\d{4}[- \t]\d{7}[- \t]\d{1}\b"#,
        flags: r#""#,
        keywords: &[],
        whole_word_keywords: &[],
        activates: r#"AE"#,
    },
    Signal {
        country: r#"AE"#,
        regex: r#"\b(\+971|00971)\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"uae"#, r#"emirates"#, r#"dubai"#, r#"abu dhabi"#],
        whole_word_keywords: &[],
        activates: r#"AE"#,
    },
    Signal {
        country: r#"IN"#,
        regex: r#"\b[A-Z]{5}\d{4}[A-Z]{1}\b"#,
        flags: r#""#,
        keywords: &[],
        whole_word_keywords: &[],
        activates: r#"IN"#,
    },
    Signal {
        country: r#"IN"#,
        regex: r#"\b\d{4}\s\d{4}\s\d{4}\b"#,
        flags: r#""#,
        keywords: &[r#"aadhaar"#, r#"aadhar"#, r#"india"#, r#"indian"#],
        whole_word_keywords: &[],
        activates: r#"IN"#,
    },
    Signal {
        country: r#"SA"#,
        regex: r#"\b1\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"saudi"#, r#"ksa"#, r#"riyadh"#, r#"national id"#, r#"iqama"#],
        whole_word_keywords: &[],
        activates: r#"SA"#,
    },
    Signal {
        country: r#"SA"#,
        regex: r#"\b(\+966|00966)\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"saudi"#, r#"ksa"#, r#"riyadh"#],
        whole_word_keywords: &[],
        activates: r#"SA"#,
    },
    Signal {
        country: r#"BR"#,
        regex: r#"\b\d{3}\.\d{3}\.\d{3}-\d{2}\b"#,
        flags: r#""#,
        keywords: &[r#"cpf"#, r#"brazil"#, r#"brasil"#, r#"brazilian"#],
        whole_word_keywords: &[],
        activates: r#"BR"#,
    },
    Signal {
        country: r#"BR"#,
        regex: r#"\b(\+55|0055)\d{11}\b"#,
        flags: r#""#,
        keywords: &[r#"brazil"#, r#"brasil"#],
        whole_word_keywords: &[],
        activates: r#"BR"#,
    },
    Signal {
        country: r#"JP"#,
        regex: r#"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b"#,
        flags: r#""#,
        keywords: &[r#"my number"#, r#"individual number"#, r#"マイナンバー"#, r#"個人番号"#, r#"japan"#, r#"japanese"#, r#"日本"#, r#"tokyo"#, r#"osaka"#, r#"nagoya"#, r#"yokohama"#],
        whole_word_keywords: &[],
        activates: r#"JP"#,
    },
    Signal {
        country: r#"JP"#,
        regex: r#"\b(\+81|0081)[ \t]?\d{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b"#,
        flags: r#""#,
        keywords: &[r#"japan"#, r#"japanese"#, r#"日本"#, r#"tokyo"#, r#"osaka"#],
        whole_word_keywords: &[],
        activates: r#"JP"#,
    },
    Signal {
        country: r#"CN"#,
        regex: r#"\b\d{17}[0-9Xx]\b"#,
        flags: r#""#,
        keywords: &[r#"resident id"#, r#"resident identity"#, r#"identity card"#, r#"id card"#, r#"身份证"#, r#"身份證"#, r#"居民身份证"#, r#"china"#, r#"chinese"#, r#"prc"#, r#"beijing"#, r#"shanghai"#, r#"shenzhen"#, r#"guangzhou"#],
        whole_word_keywords: &[],
        activates: r#"CN"#,
    },
    Signal {
        country: r#"CN"#,
        regex: r#"\b(\+86|0086)[ \t]?1[3-9]\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"china"#, r#"chinese"#, r#"prc"#, r#"beijing"#, r#"shanghai"#, r#"shenzhen"#, r#"guangzhou"#],
        whole_word_keywords: &[],
        activates: r#"CN"#,
    },
    Signal {
        country: r#"KR"#,
        regex: r#"\b\d{6}-?[1-8]\d{6}\b"#,
        flags: r#""#,
        keywords: &[r#"resident registration"#, r#"resident number"#, r#"rrn"#, r#"jumin"#, r#"주민등록번호"#, r#"주민번호"#, r#"korea"#, r#"korean"#, r#"seoul"#, r#"busan"#, r#"incheon"#],
        whole_word_keywords: &[],
        activates: r#"KR"#,
    },
    Signal {
        country: r#"KR"#,
        regex: r#"\b(\+82|0082)[ \t]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b"#,
        flags: r#""#,
        keywords: &[r#"korea"#, r#"korean"#, r#"seoul"#, r#"busan"#, r#"incheon"#],
        whole_word_keywords: &[],
        activates: r#"KR"#,
    },
    Signal {
        country: r#"GH"#,
        regex: r#"\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b"#,
        flags: r#""#,
        keywords: &[r#"ghana card"#, r#"ghanacard"#, r#"ghana"#, r#"accra"#, r#"kumasi"#, r#"nia pin"#, r#"gra tin"#],
        whole_word_keywords: &[],
        activates: r#"GH"#,
    },
    Signal {
        country: r#"GH"#,
        regex: r#"\b(\+233|00233)[ \t]?\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"ghana"#, r#"ghanaian"#, r#"accra"#, r#"kumasi"#, r#"tema"#],
        whole_word_keywords: &[],
        activates: r#"GH"#,
    },
    Signal {
        country: r#"IT"#,
        regex: r#"\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b"#,
        flags: r#""#,
        keywords: &[r#"codice fiscale"#, r#"cod. fisc"#, r#"c.f."#, r#"anagrafe tributaria"#, r#"italy"#, r#"italia"#, r#"italian"#, r#"italiana"#, r#"roma"#, r#"milano"#, r#"napoli"#, r#"torino"#],
        whole_word_keywords: &[],
        activates: r#"IT"#,
    },
    Signal {
        country: r#"IT"#,
        regex: r#"\b(\+39|0039)[ \t]?\d{9,11}\b"#,
        flags: r#""#,
        keywords: &[r#"italy"#, r#"italia"#, r#"italian"#, r#"italiana"#, r#"roma"#, r#"milano"#, r#"napoli"#, r#"torino"#],
        whole_word_keywords: &[],
        activates: r#"IT"#,
    },
    Signal {
        country: r#"KE"#,
        regex: r#"\b[AP]\d{9}[A-Z]\b"#,
        flags: r#""#,
        keywords: &[r#"kra"#, r#"itax"#, r#"tax pin"#, r#"kenya"#, r#"kenyan"#, r#"nairobi"#, r#"mombasa"#, r#"kisumu"#],
        whole_word_keywords: &[],
        activates: r#"KE"#,
    },
    Signal {
        country: r#"KE"#,
        regex: r#"\b(\+254|00254)[ \t]?\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"kenya"#, r#"kenyan"#, r#"nairobi"#, r#"mombasa"#, r#"kisumu"#],
        whole_word_keywords: &[],
        activates: r#"KE"#,
    },
    Signal {
        country: r#"MU"#,
        regex: r#"\b[123578]\d{7}\b"#,
        flags: r#""#,
        keywords: &[r#"mauritius"#, r#"mauritian"#, r#"port louis"#, r#"mauritius revenue"#, r#"mra tan"#],
        whole_word_keywords: &[],
        activates: r#"MU"#,
    },
    Signal {
        country: r#"MU"#,
        regex: r#"\b(\+230|00230)[ \t]?\d{7,8}\b"#,
        flags: r#""#,
        keywords: &[r#"mauritius"#, r#"mauritian"#, r#"port louis"#],
        whole_word_keywords: &[],
        activates: r#"MU"#,
    },
    Signal {
        country: r#"MX"#,
        regex: r#"\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b"#,
        flags: r#""#,
        keywords: &[r#"rfc"#, r#"homoclave"#, r#"contribuyentes"#, r#"mexico"#, r#"méxico"#, r#"mexican"#, r#"mexicano"#, r#"cdmx"#, r#"guadalajara"#, r#"monterrey"#],
        whole_word_keywords: &[],
        activates: r#"MX"#,
    },
    Signal {
        country: r#"MX"#,
        regex: r#"\b(\+52|0052)[ \t]?\d{10}\b"#,
        flags: r#""#,
        keywords: &[r#"mexico"#, r#"méxico"#, r#"mexican"#, r#"mexicano"#, r#"cdmx"#, r#"guadalajara"#, r#"monterrey"#],
        whole_word_keywords: &[],
        activates: r#"MX"#,
    },
    Signal {
        country: r#"MY"#,
        regex: r#"\b\d{6}-\d{2}-\d{4}\b"#,
        flags: r#""#,
        keywords: &[r#"mykad"#, r#"kad pengenalan"#, r#"nric"#, r#"malaysia"#, r#"malaysian"#, r#"kuala lumpur"#, r#"johor"#, r#"penang"#, r#"putrajaya"#, r#"selangor"#],
        whole_word_keywords: &[],
        activates: r#"MY"#,
    },
    Signal {
        country: r#"MY"#,
        regex: r#"\b\d{12}\b"#,
        flags: r#""#,
        keywords: &[r#"mykad"#, r#"my kad"#, r#"kad pengenalan"#, r#"mykid"#],
        whole_word_keywords: &[],
        activates: r#"MY"#,
    },
    Signal {
        country: r#"MY"#,
        regex: r#"\b(\+60|0060)[ \t]?\d{9,10}\b"#,
        flags: r#""#,
        keywords: &[r#"malaysia"#, r#"malaysian"#, r#"kuala lumpur"#, r#"johor"#, r#"penang"#],
        whole_word_keywords: &[],
        activates: r#"MY"#,
    },
    Signal {
        country: r#"PK"#,
        regex: r#"\b\d{5}-\d{7}-\d\b"#,
        flags: r#""#,
        keywords: &[r#"cnic"#, r#"nadra"#, r#"pakistan"#, r#"pakistani"#, r#"karachi"#, r#"lahore"#, r#"islamabad"#, r#"rawalpindi"#, r#"شناختی"#],
        whole_word_keywords: &[],
        activates: r#"PK"#,
    },
    Signal {
        country: r#"PK"#,
        regex: r#"\b\d{13}\b"#,
        flags: r#""#,
        keywords: &[r#"cnic"#, r#"nadra"#, r#"شناختی"#],
        whole_word_keywords: &[],
        activates: r#"PK"#,
    },
    Signal {
        country: r#"PK"#,
        regex: r#"\b(\+92|0092)[ \t]?3\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"pakistan"#, r#"pakistani"#, r#"karachi"#, r#"lahore"#, r#"islamabad"#],
        whole_word_keywords: &[],
        activates: r#"PK"#,
    },
    Signal {
        country: r#"SG"#,
        regex: r#"\b[STFGM]\d{7}[A-Z]\b"#,
        flags: r#""#,
        keywords: &[r#"nric"#, r#"singpass"#, r#"cpf"#, r#"iras"#, r#"singapore"#, r#"singaporean"#],
        whole_word_keywords: &[],
        activates: r#"SG"#,
    },
    Signal {
        country: r#"SG"#,
        regex: r#"\b(\+65|0065)[ \t]?[689]\d{3}[ \t]?\d{4}\b"#,
        flags: r#""#,
        keywords: &[r#"singapore"#, r#"singaporean"#],
        whole_word_keywords: &[],
        activates: r#"SG"#,
    },
    Signal {
        country: r#"TH"#,
        regex: r#"\b\d-\d{4}-\d{5}-\d{2}-\d\b"#,
        flags: r#""#,
        keywords: &[r#"national id"#, r#"thai"#, r#"thailand"#, r#"เลขประจำตัวประชาชน"#, r#"บัตรประชาชน"#, r#"bangkok"#, r#"promptpay"#],
        whole_word_keywords: &[],
        activates: r#"TH"#,
    },
    Signal {
        country: r#"TH"#,
        regex: r#"\b\d{13}\b"#,
        flags: r#""#,
        keywords: &[r#"thai id"#, r#"thailand"#, r#"เลขประจำตัวประชาชน"#, r#"บัตรประชาชน"#, r#"promptpay"#],
        whole_word_keywords: &[],
        activates: r#"TH"#,
    },
    Signal {
        country: r#"TH"#,
        regex: r#"\b(\+66|0066)[ \t]?\d{9}\b"#,
        flags: r#""#,
        keywords: &[r#"thailand"#, r#"thai"#, r#"bangkok"#, r#"phuket"#, r#"chiang mai"#],
        whole_word_keywords: &[],
        activates: r#"TH"#,
    },
    Signal {
        country: r#"ID"#,
        regex: r#"\b\d{16}\b"#,
        flags: r#""#,
        keywords: &[r#"nomor induk kependudukan"#, r#"kartu tanda penduduk"#, r#"dukcapil"#],
        whole_word_keywords: &[r#"nik"#, r#"e-ktp"#, r#"ektp"#, r#"ktp"#, r#"npwp"#],
        activates: r#"ID"#,
    },
    Signal {
        country: r#"ID"#,
        regex: r#"\b(\+62|0062)[ \t]?\d{9,12}\b"#,
        flags: r#""#,
        keywords: &[r#"indonesia"#, r#"indonesian"#, r#"jakarta"#, r#"surabaya"#, r#"bandung"#, r#"medan"#, r#"bali"#],
        whole_word_keywords: &[],
        activates: r#"ID"#,
    },
];
